version: "3.7"
services: 
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports: 
            - "3306:3306"
        volumes:
            - /var/lib/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: test
            MYSQL_PASSWORD: test_pass
            MYSQL_ROOT_HOST: "%"
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080